# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89a7beb5d55bddb6717e75e8a464b75b9c2c53652d2daa2181cfd6a0081f0fd543acfe96fc86529838a3ff22d3ed0bd1216ad9369a78cad4be1b62582297347e

test:
  secret_key_base: 6db510e5278ec4d37011bc3e33eccf46583dc5a8ad2f713b20fab5f2442ff7bcf962ba6ce3414f62b2513eb30dc6d697147787fb24c24c909f9baf4c89da3ed1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
